### ISSUE TITLE
Not Opening Text Editor

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#11]
I click open, then get this: Looking for lesson...
/Users/willmclellarn/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)

**Comment by AnnJohn** [comment]
Hi @Terco30 sorry for the trouble you're having. For immediate assistance, please use the Ask a Question tool on Learn and someone from our support team will get back to you right away. Thanks!

**Comment by ghost** [comment]
cool, did so!
