### ISSUE TITLE
Nitrous is acting buggy

### ISSUE THREAD

**Issue by milothiesen** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#13]
Nitrous keeps freezing, I have to refresh a lot, keeps asking about SSH. It's hard to work right now because I can't tell if my code is right or not, because it keeps freezing. I don't know if it's me or Nitrous that is the problem..

**Comment by AnnJohn** [comment]
Hi @mailethiesen sorry for the trouble you're having. Please use the Ask a Question tool in Learn and someone from our support team will get back to you right away. Thanks!
