### ISSUE TITLE
First Lab Issue

### ISSUE THREAD

**Issue by ccapacchione** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#14]
I can not ask a question nor am I able to get my terminal to work. Everytime I open it, it tells me that the commands are wrong and that I should logout. How can I fix this problem? I am using OS X on my MacBook Pro

**Comment by AnnJohn** [comment]
Hi @ccapacchione sorry for the delay. Is this still an issue that you're having? Thanks

**Comment by ccapacchione** [comment]
I seemed to have figured it out, thank you for your help though.

**Comment by AnnJohn** [comment]
Thanks!
