### ISSUE TITLE
Sublime issue

### ISSUE THREAD

**Issue by mjrode** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#17]
When attempting to open the first lesson with Sublime I get prompted to enter my license key. I am not sure if this is because I had previously had Sublime installed on my computer or if I need to upgrade to the paid version of sublime in order to use this with Learn.

**Comment by AnnJohn** [comment]
Hi @mjrode you shouldn't need to install a license key as Sublime should be free. But for immediate help, please use the Ask a Question tool in Learn and someone can answer your questions right away. Thanks!
