### ISSUE TITLE
Can't select the Open option Above

### ISSUE THREAD

**Issue by saraahmad1114** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#18]
I'm trying to do as the lab requests by hitting the "open" option and it is faded in and I can't even begin and the lab or go ahead

**Comment by AnnJohn** [comment]
Hi @saraahmad1114 sorry for the issue you're having. Please use the Ask a Question tool in Learn and someone from our Learn support staff will get back to you right away.

**Comment by saraahmad1114** [comment]
@AnnJohn thanks so much for the response but I did do that and I followed the instructions provided however nothing changed and I still have the same problem
