### ISSUE TITLE
Question on First Lab-Learn CLI

### ISSUE THREAD

**Issue by Jbusername** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#19]
https://github.com/learn-co-curriculum/first-lab-ruby-learn-cli-osx

I'm trying to do my first lab. How do I get the "Open" tab to work?

**Comment by AnnJohn** [comment]
Hi @Jbusername sorry for the issue that you're having. Please use the Ask a Question tool in Learn and someone from our Learn team will get back to you right away.
