### ISSUE TITLE
Can't learn submit

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#21]
It looks like you have no changes to commit. Will still try updating your submission...
Pushing changes to GitHub...
/Users/dominicfaulring/.rvm/gems/ruby-2.2.3/gems/git-1.2.9.1/lib/git/lib.rb:917:in `command': git '--git-dir=/Users/dominicfaulring/Development/code/first-lab-ruby-learn-cli-osx-intro-to-learn/.git' '--work-tree=/Users/dominicfaulring/Development/code/first-lab-ruby-learn-cli-osx-intro-to-learn' push 'origin' 'master'  2>&1:ERROR: Permission to dfaulring/first-lab-ruby-learn-cli-osx-intro-to-learn.git denied to dominicfaulring. (Git::GitExecuteError)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
    from /Users/dominicfaulring/.rvm/gems/ruby-2.2.3/gems/git-1.2.9.1/lib/git/lib.rb:727:in `push'
    from /Users/dominicfaulring/.rvm/gems/ruby-2.2.3/gems/git-1.2.9.1/lib/git/base.rb:329:in`push'
    from /Users/dominicfaulring/.rvm/gems/ruby-2.2.3/gems/learn-submit-1.1.7/lib/learn_submit/submission/git_interactor.rb:123:in `block in push!'
    from /Users/dominicfaulring/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:88:in`block in timeout'
    from /Users/dominicfaulring/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
    from /Users/dominicfaulring/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:32:in`catch'
    from /Users/dominicfaulring/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:32:in `catch'
    from /Users/dominicfaulring/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:103:in`timeout'
    from /Users/dominicfaulring/.rvm/gems/ruby-2.2.3/gems/learn-submit-1.1.7/lib/learn_submit/submission/git_interactor.rb:122:in `push!'
    from /Users/dominicfaulring/.rvm/gems/ruby-2.2.3/gems/learn-submit-1.1.7/lib/learn_submit/submission/git_interactor.rb:23:in`commit_and_push'
    from /Users/dominicfaulring/.rvm/gems/ruby-2.2.3/gems/learn-submit-1.1.7/lib/learn_submit/submission.rb:46:in `commit_and_push!'
    from /Users/dominicfaulring/.rvm/gems/ruby-2.2.3/gems/learn-submit-1.1.7/lib/learn_submit/submission.rb:22:in`create'
    from /Users/dominicfaulring/.rvm/gems/ruby-2.2.3/gems/learn-submit-1.1.7/lib/learn_submit/submission.rb:6:in `create'
    from /Users/dominicfaulring/.rvm/gems/ruby-2.2.3/gems/learn-submit-1.1.7/bin/learn-submit:15:in`<top (required)>'
    from /Users/dominicfaulring/.rvm/gems/ruby-2.2.3/bin/learn-submit:23:in `load'
    from /Users/dominicfaulring/.rvm/gems/ruby-2.2.3/bin/learn-submit:23:in`<main>'
    from /Users/dominicfaulring/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
    from /Users/dominicfaulring/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in`<main>'

**Comment by AnnJohn** [comment]
Hi @dfaulring sorry for the issue that you're having. Since this isn't a generic issue, please use the Ask a Question tool within Learn and someone will get back to you right away. Thanks!
