### ISSUE TITLE
My Open button is deactivated.

### ISSUE THREAD

**Issue by RobertoMII** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#22]
How do I access the Learn CLI? My Open button is deactivated.

**Comment by AnnJohn** [comment]
Hi @RobertoMII for immediate help with this, please use the Ask a Question tool in Learn and someone from our support team will get back to you right away. Thanks

**Comment by RobertoMII** [comment]
Hi @AnnJohn I did and they asked me to 'Raise an issue'

**Comment by AnnJohn** [comment]
@RobertoMII Actually it's best to file a bug report. If you hover over your profile pic in Learn, you'll see an option to Report a Bug. Issues are specifically for issues related to the curriculum content. Thanks!
