### ISSUE TITLE
No green lights

### ISSUE THREAD

**Issue by brittonb3** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#24]
Hey,
I followed the lesson, finished and submitted it but the green lights on the learn site never came on. I don't want to move on without them coming on and saying I finished the lesson. In the terminal it says that I finished the lesson. I hope you can help!

Thanks, 

Britton

**Comment by AnnJohn** [comment]
hi @brittonb3 this looks like a technical bug. If you hover over your profile pic in Learn  you should see an option to Report a Bug. 

Also for immediate help, please use the Ask a Question tool in Learn and someone from our support team should help you out. Thanks
