### ISSUE TITLE
Capitalize "learn" in title

### ISSUE THREAD

**Issue by kenmhaggerty** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#25]
So that the exercise reads "First Lab – Learn CLI" and not "First Lab – learn CLI".

**Comment by AnnJohn** [comment]
thanks this is an issue that involves renaming the repo on Github which can cause some larger errors. Thanks for raising this; we'll close it for now but will note it.

**Comment by kenmhaggerty** [comment]
Sounds good. I'll refrain from submitting similar bugs for further repos.
