### ISSUE TITLE
"Open" button launches Ruby 2.2.1

### ISSUE THREAD

**Issue by wildcatblue** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#28]
When I press the open button on the page, it opens my terminal in Ruby version 2.2.1. I have upgraded to 2.2.3. Since it is an older version, I have found out that the "learn" command may not work. So when I press the "Open" button, I see this:

Last login: Tue Mar 15 12:57:43 on ttys001
/tmp/tmp_open.sh ; exit;
[~] ruby-2.2.1 $ /tmp/tmp_open.sh ; exit;
Looking for lesson...
Bundling...
sh: subl: command not found
Opening lesson...
Done.
[~/Development/code/first-lab-ruby-learn-cli-osx-q-000] ruby-2.2.1 $ 

When I type the "learn" command, I receive this

[~/Development/code/first-lab-ruby-learn-cli-osx-q-000] ruby-2.2.1 $ learn
/Users/Home/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2162:in `method_missing': undefined method`this' for #<Gem::Specification:0x3ff6e9084830 thor-0.19.1> (NoMethodError)
    from /Users/Home/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
    from /Users/Home/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:64:in`require'
    from /Users/Home/.rvm/gems/ruby-2.2.1/gems/learn-co-3.3.0/lib/learn.rb:1:in `<top (required)>'
    from /Users/Home/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in`require'
    from /Users/Home/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
    from /Users/Home/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in`require'
    from /Users/Home/.rvm/gems/ruby-2.2.1/gems/learn-co-3.3.0/bin/learn:3:in `<top (required)>'
    from /Users/Home/.rvm/gems/ruby-2.2.1/bin/learn:22:in`load'
    from /Users/Home/.rvm/gems/ruby-2.2.1/bin/learn:22:in `<main>'
    from /Users/Home/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in`eval'
    from /Users/Home/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by AnnJohn** [comment]
hi @andrewstone8 sorry for the delay on this and if for some reason this issue wasn't resolved already, could you use the Ask a Question tool in Learn and/or file a bug report? If you hover over your profile pic in Learn, you'll see an option to report a bug. Thanks!
