### ISSUE TITLE
Unable to clone lesson

### ISSUE THREAD

**Issue by shreekal** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#29]
Last login: Tue Mar 29 22:48:34 on ttys000
/tmp/tmp_open.sh ; exit;
[22:49:39] ~
// ♥ /tmp/tmp_open.sh ; exit;
Looking for lesson...
Forking lesson...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
Cloning lesson...
Cannot clone this lesson right now. Please try again.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by AnnJohn** [comment]
Hi @shreekal since this is a technical issue, could you use the Ask a Question tool in Learn and/or file a bug report? If you hover over your profile pic in Learn, you'll see an option to report a bug. Thanks!
