### ISSUE TITLE
"Open" button not clickable

### ISSUE THREAD

**Issue by mikeandkoda** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#33]
"Open" button not clickable at top of page on first lab. I found a few other questions about this posted by students, but no answers. Please help.

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the _content_ of this lesson. If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to ASAP.

**Comment by mikeandkoda** [comment]
Hi Charles,

I have submitted a bug report for this. I also posted a question about the
problem I'm having but I noticed that several other students posted the
same question over the past few months and not a single one of them
received an answer. This is a bit frustrating as I am just trying to get
started and I cant open my first lab. Currently I am stuck on lesson 8 in
the Intro to Learn (OSX) track. Please help.

On Wed, Jun 22, 2016 at 12:54 PM, Charles Pletcher <notifications@github.com

**Comment by pletcher** [comment]
Hi @mikeandkoda, it sounds like you might be using an old version of the Learn app. Unfortunately, the best workaround is simply to run `learn open` from Terminal.app.

I've updated the instructions on this lab to reflect this change. Best of luck!

**Comment by mikeandkoda** [comment]
Great thank you.
