### ISSUE TITLE
Error with Psych Gem

### ISSUE THREAD

**Issue by snsavage** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#4]
I kept getting an error similar to this when using the `learn` command: 

```
/Users/snsavage/.rvm/gems/ruby-2.1.1/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:4:in `<class:PsychResolver>': uninitialized constant Psych::Nodes (NameError)
```

The solution from djmtype listed here https://github.com/dtao/safe_yaml/issues/72 solved my problem.  I had to run `gem uninstall psych -v 2.0.5` to get the `learn` CLI to run.

**Comment by aviflombaum** [comment]
Thanks for the tip @snsavage, we'll look into preventing this for future learners.

cc @loganhasson

**Comment by loganhasson** [comment]
thanks @snsavage !

@aviflombaum moving this over to the gem's issues.
