### ISSUE TITLE
problem with opening/cloning lesson

### ISSUE THREAD

**Issue by bgrinberg** [learn-co-curriculum/first-lab-ruby-learn-cli-osx#5]
Last login: Fri Oct 16 15:19:56 on ttys001
/tmp/tmp_open.sh ; exit;
[15:20:37](master) ~
// ♥ /tmp/tmp_open.sh ; exit;
Looking for lesson...
Forking lesson...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
Cannot clone this lesson right now. Please try again.
logout

[Process completed]

**Comment by AnnJohn** [comment]
Hi @bgrinberg sorry for the trouble you're having. Since it look like you need immediate help, please use the "Ask a Question" chat on Learn and someone will get back to you right away. Thanks!
